#!/bin/sh -ex

install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

# setup pinning
REPO_LABEL="home:emby"
cat >/etc/apt/preferences.d/emby<<EOF
Package: *
Pin: release l=$REPO_LABEL
Pin-Priority: 100
Package: libmono* mono* libemby* emby-server
Pin: release o=obs://build.opensuse.org/home:emby/Debian_8.0
Pin-Priority: 500
EOF

# install emby dependencies (from 3rd party repo)
install mono-runtime libembymagickcore-6.q8-2 libembymagickwand-6.q8-2

# install emby and configure it, HACK since emby blocks the shell when it starts from the deb install
install emby-server &
EMBY_PID=$!

while [ ! -f /var/run/emby-server.pid ]
do
  sleep 10
done

# Delay until emby has finished starting
EMBY_SERVER=127.0.0.1
EMBY_PORT=8096
CURL="curl --output /dev/null --silent --head --fail"
until $($CURL http://$EMBY_SERVER:$EMBY_PORT); do
    sleep 5
done

# Rename the samba service
CONF=/etc/samba/smb.conf
sed -i "s|FILESERVER|MEDIASERVER|" $CONF
sed -i "s|FileServer|MediaServer|" $CONF

# Change default group to users
usermod -g users emby
chgrp -R users /usr/lib/emby-server
chgrp -R users /var/lib/emby-server/*

# Change group assigned to emby
CONF=/etc/emby-server.conf
echo "EMBY_GROUP=\"users\"" >> $CONF

# Make restart script installed by emby executable
chmod +x /usr/lib/emby-server/restart.sh

#Setup default media folders
mkdir -p /srv/storage/Music
chown emby:users /srv/storage/Music
chmod g+w /srv/storage/Music

mkdir -p /srv/storage/Movies
chown emby:users /srv/storage/Movies
chmod g+w /srv/storage/Movies

mkdir -p /srv/storage/TVShows
chown emby:users /srv/storage/TVShows
chmod g+w /srv/storage/TVShows

mkdir -p /srv/storage/Photos
chown emby:users /srv/storage/Photos
chmod g+w /srv/storage/Photos

# Replace text in README
CONF=/srv/storage/README.txt
sed -i "s|File Server|Media Server|" $CONF

# Configure Emby through web interface (Now handled in inithooks)
# CURL="curl -c /tmp/cookie -b /tmp/cookie http://127.0.0.1:8096"

# ${CURL}'/emby/startup/Configuration' --data 'UICulture=en-us' --data 'EnableInternetProviders=true' --data 'SaveLocalMeta=false' --data 'MetadataCountryCode=US' --data 'PreferredMetadataLanguage=en' > /dev/null
# ${CURL}'/emby/startup/User' --data 'Name=emby' > /dev/null
# ${CURL}'/emby/Library/VirtualFolders?collectionType=music&refreshLibrary=false&name=Music' --data '{"Paths":["/srv/storage/Music"]}' --header "Content-Type: application/json; charset=UTF-8" > /dev/null
# ${CURL}'/emby/Library/VirtualFolders?collectionType=movies&refreshLibrary=false&name=Movies' --data '{"Paths":["/srv/storage/Movies"]}' --header "Content-Type: application/json; charset=UTF-8" > /dev/null
# ${CURL}'/emby/Library/VirtualFolders?collectionType=tvshows&refreshLibrary=false&name=TV' --data '{"Paths":["/srv/storage/TVShows"]}' --header "Content-Type: application/json; charset=UTF-8" > /dev/null
# ${CURL}'/emby/Library/VirtualFolders?collectionType=photos&refreshLibrary=false&name=Photos' --data '{"Paths":["/srv/storage/Photos"]}' --header "Content-Type: application/json; charset=UTF-8" > /dev/null
# ${CURL}'/emby/System/Configuration/MetatdataPlugins/Autoset' --data '' > /dev/null
# ${CURL}'/emby/Startup/Complete' --data '' > /dev/null

# Stop the service
/etc/init.d/emby-server stop

# Let the remaining setup tasks complete
wait $EMBY_PID
#sleep 300

# Installed as part of Emby setup
/etc/init.d/dbus stop

# Remove Emby data directory (Necessary for emby to run properly in final appliance, Regenerated when emby first starts)
rm -r /var/lib/emby-server

# Enable Emby to start at boot
systemctl enable emby-server.service

# add TurnKey credit to log in page
mkdir -p /var/lib/emby-server/config/
mv /usr/local/src/emby-branding.xml  /var/lib/emby-server/config/branding.xml

