#!/bin/bash -e
# setup Emby media server

. /etc/default/inithooks

EMBY_SERVER=127.0.0.1
EMBY_PORT=8096
CURL="curl --output /dev/null --silent --head --fail"

emby_running () {
    local pidfile='/run/emby-server.pid'
    [ -e "$pidfile" ] && kill -0 $( cat $pidfile )
}

# Start Emby server if not running
if ! emby_running; then
    service emby-server start
fi

# Delay until emby has finished starting
until $($CURL http://$EMBY_SERVER:$EMBY_PORT); do
    echo -n .
    sleep 5
done

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/emby-server.py --pass="$APP_PASS"

if [ "$APP_PASS" != "" ]; then
    echo $APP_PASS > /etc/embypass
else
    rm -f /etc/embypass
fi

if emby_running; then
    service emby-server stop
fi
